version: "3.7"
services:
  api:
    container_name: api
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 4000:4000
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    environment:
      - NODE_ENV=production
    links:
      - mongodb

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  mongodb:
    container_name: mongodb
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - "mongo_data:/data/db"

networks:
  internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mongo_data:
